//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculadora.ServiceReferenceCalculadora {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfLaboratorio.Calculadora")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Numero", Namespace="http://schemas.datacontract.org/2004/07/Core.Numero")]
    [System.SerializableAttribute()]
    public partial class Numero : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string elNumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int laBaseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string elNumero {
            get {
                return this.elNumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.elNumeroField, value) != true)) {
                    this.elNumeroField = value;
                    this.RaisePropertyChanged("elNumero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int laBase {
            get {
                return this.laBaseField;
            }
            set {
                if ((this.laBaseField.Equals(value) != true)) {
                    this.laBaseField = value;
                    this.RaisePropertyChanged("laBase");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceCalculadora.IMiCalculadora")]
    public interface IMiCalculadora {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiCalculadora/GetData", ReplyAction="http://tempuri.org/IMiCalculadora/GetDataResponse")]
        string GetData(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiCalculadora/GetData", ReplyAction="http://tempuri.org/IMiCalculadora/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiCalculadora/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IMiCalculadora/GetDataUsingDataContractResponse")]
        Calculadora.ServiceReferenceCalculadora.CompositeType GetDataUsingDataContract(Calculadora.ServiceReferenceCalculadora.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiCalculadora/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IMiCalculadora/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<Calculadora.ServiceReferenceCalculadora.CompositeType> GetDataUsingDataContractAsync(Calculadora.ServiceReferenceCalculadora.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiCalculadora/RealizarOperacionBinaria", ReplyAction="http://tempuri.org/IMiCalculadora/RealizarOperacionBinariaResponse")]
        Calculadora.ServiceReferenceCalculadora.Numero RealizarOperacionBinaria(char elOperador, Calculadora.ServiceReferenceCalculadora.Numero elPrimerNumero, Calculadora.ServiceReferenceCalculadora.Numero elSegundoNumero, Calculadora.ServiceReferenceCalculadora.Numero Resultado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiCalculadora/RealizarOperacionBinaria", ReplyAction="http://tempuri.org/IMiCalculadora/RealizarOperacionBinariaResponse")]
        System.Threading.Tasks.Task<Calculadora.ServiceReferenceCalculadora.Numero> RealizarOperacionBinariaAsync(char elOperador, Calculadora.ServiceReferenceCalculadora.Numero elPrimerNumero, Calculadora.ServiceReferenceCalculadora.Numero elSegundoNumero, Calculadora.ServiceReferenceCalculadora.Numero Resultado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMiCalculadoraChannel : Calculadora.ServiceReferenceCalculadora.IMiCalculadora, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MiCalculadoraClient : System.ServiceModel.ClientBase<Calculadora.ServiceReferenceCalculadora.IMiCalculadora>, Calculadora.ServiceReferenceCalculadora.IMiCalculadora {
        
        public MiCalculadoraClient() {
        }
        
        public MiCalculadoraClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MiCalculadoraClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MiCalculadoraClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MiCalculadoraClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(string value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(string value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public Calculadora.ServiceReferenceCalculadora.CompositeType GetDataUsingDataContract(Calculadora.ServiceReferenceCalculadora.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<Calculadora.ServiceReferenceCalculadora.CompositeType> GetDataUsingDataContractAsync(Calculadora.ServiceReferenceCalculadora.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public Calculadora.ServiceReferenceCalculadora.Numero RealizarOperacionBinaria(char elOperador, Calculadora.ServiceReferenceCalculadora.Numero elPrimerNumero, Calculadora.ServiceReferenceCalculadora.Numero elSegundoNumero, Calculadora.ServiceReferenceCalculadora.Numero Resultado) {
            return base.Channel.RealizarOperacionBinaria(elOperador, elPrimerNumero, elSegundoNumero, Resultado);
        }
        
        public System.Threading.Tasks.Task<Calculadora.ServiceReferenceCalculadora.Numero> RealizarOperacionBinariaAsync(char elOperador, Calculadora.ServiceReferenceCalculadora.Numero elPrimerNumero, Calculadora.ServiceReferenceCalculadora.Numero elSegundoNumero, Calculadora.ServiceReferenceCalculadora.Numero Resultado) {
            return base.Channel.RealizarOperacionBinariaAsync(elOperador, elPrimerNumero, elSegundoNumero, Resultado);
        }
    }
}
